# Generated by Django 3.2.7 on 2021-09-26 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='appointment',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='client',
            managers=[
            ],
        ),
    ]
