# Generated by Django 3.2.7 on 2021-09-26 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymApp', '0002_auto_20210926_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounsellingAssessment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance', models.BooleanField()),
                ('intakeDate', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('case_category', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=100)),
                ('appointment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymApp.appointment')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymApp.client')),
            ],
        ),
    ]
