# Generated by Django 3.2.7 on 2021-09-27 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymApp', '0003_counsellingassessment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counsellingassessment',
            name='client_id',
        ),
    ]
