# Generated by Django 3.2.7 on 2021-10-05 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymApp', '0004_remove_counsellingassessment_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellingassessment',
            name='client_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mymApp.client'),
            preserve_default=False,
        ),
    ]
